import {readFileSync,existsSync} from 'node:fs';import {join} from 'node:path';
import {walk} from './editorial.mjs';import {allUnits} from '../src/data/catalog.mjs';
const errors=[];const htmlFiles=walk('dist').filter(f=>f.endsWith('.html'));const index=new Map(htmlFiles.map(f=>[f,readFileSync(f,'utf8')]));
for(const [f,html]of index){const ids=new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));for(const m of html.matchAll(/href="([^"]*)"/g)){const href=m[1];if(href.startsWith('#')){if(href.length>1&&!ids.has(decodeURIComponent(href.slice(1))))errors.push(`${f}: missing anchor ${href}`);}else if(href.startsWith('/')&&!href.startsWith('//')){const url=new URL(href,'http://local');const path=join('dist',decodeURIComponent(url.pathname));const dest=url.pathname.endsWith('/')?join(path,'index.html'):path;if(!existsSync(dest))errors.push(`${f}: missing link ${href}`);else if(url.hash&&dest.endsWith('.html')){const target=index.get(dest)||readFileSync(dest,'utf8');if(!target.includes(`id="${decodeURIComponent(url.hash.slice(1))}"`))errors.push(`${f}: missing target anchor ${href}`);}}}}
for(const e of allUnits)for(const lang of ['zh','en']){const f=`dist/${lang}/wiki/${e.id}/index.html`;const html=index.get(f)||'';if(!html.includes(e.title[lang].replaceAll('&','&amp;')))errors.push(`${f}: missing title`);const api=`dist/api/${lang}/${e.id}.json`;if(!existsSync(api)||JSON.parse(readFileSync(api,'utf8')).id!==e.id)errors.push(`${api}: missing bilingual content export`);if(e.examples&&(html.match(/class="quiz"/g)||[]).length<2)errors.push(`${f}: missing server-rendered exercises`);}
for(const id of ['affirming-consequent','denying-antecedent','affirming-disjunct','denying-conjunct'])if(!index.get(`dist/zh/wiki/${id}/index.html`)?.includes('class="logic-lab"'))errors.push(`${id}: truth table missing`);
const contentIndex=JSON.parse(readFileSync('dist/api/index.json','utf8'));
if(contentIndex.units.length!==170)errors.push('Bilingual index must contain 170 units');
for(const unit of contentIndex.units)for(const lang of ['zh','en']){const data=JSON.parse(readFileSync(`dist${unit.routes[lang].content}`,'utf8'));if(data.bilingualVersion!==unit.bilingualVersion)errors.push(`${unit.id}: index/version mismatch`);for(const q of unit.exercises){const exported=data.content.exercises.find(x=>x.id===q.id);if(!exported||exported.revision!==q.revision||JSON.stringify(exported.acceptedAnswerIds)!==JSON.stringify(q.acceptedAnswerIds))errors.push(`${unit.id}: exercise export mismatch`);}}
if(!existsSync('dist/pagefind/pagefind.js'))errors.push('Pagefind index missing');if(!existsSync('dist/sitemap.xml'))errors.push('Sitemap missing');
if(errors.length){console.error(errors.slice(0,60).join('\n'));console.error(`${errors.length} build errors`);process.exit(1);}console.log(`Static verification passed: ${htmlFiles.length} HTML files, all internal links and anchors, 340 language exports, exercises, math labs, Pagefind and sitemap.`);
